#!/bin/bash

. ${PENTAHO_HOME}/setup/postgres-functions

DB=${DASH_TARGET}

echo "alterDB $DB $SIRED_DASH_IP $SIRED_DASH_PORTA $SIRED_DASH_USR $SIRED_DASH_PSW "
alterDB $DB $SIRED_DASH_IP $SIRED_DASH_PORTA $SIRED_DASH_USR $SIRED_DASH_PSW
